services:
  nginx:
    image: nginx:latest
    container_name: wordock-nginx
    ports:
      - "${WP_PORT}:80"
    volumes:
      - ./src:/var/www/html
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - wordock-network

  php:
    build:
      context: .
      dockerfile: ./config/php/Dockerfile
    container_name: wordock-php
    volumes:
      - ./src:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - wordock-network

  db:
    image: mysql:5.7
    container_name: wordock-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WP_DB_NAME}
      MYSQL_USER: ${WP_DB_USER}
      MYSQL_PASSWORD: ${WP_DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - wordock-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: wordock-phpmyadmin
    environment:
      PMA_HOST: db                 # Link to the MySQL service (use service name as the host)
      PMA_PORT: 3306               # MySQL port
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}  # Root password from .env
    ports:
      - "9080:80"                  # Access phpMyAdmin on localhost:8080
    depends_on:
      - db                         # Ensure MySQL starts before phpMyAdmin
    networks:
      - wordock-network

  mailhog:
    image: mailhog/mailhog
    container_name: wordock-mailhog
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI for email testing
    networks:
      - wordock-network

volumes:
  db-data:

networks:
  wordock-network:
